[default]
auto_detect_solc = false
solc_version = '0.8.7'
src = 'contracts'
out = 'forge/out'
test = 'forge/test/'
libs = ['node_modules']
optimizer = true
optimizer_runs = 200

[ci]
verbosity = 4

# See more config options https://book.getfoundry.sh/reference/config.html