/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PoolKeeper, PoolKeeperInterface } from "../PoolKeeper";

const _abi = [
  {
    inputs: [],
    name: "OPERATOR",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060d18061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063983d273714602d575b600080fd5b60336047565b604051603e91906078565b60405180910390f35b7f523a704056dcd17bcf83bed8b68c59416dac1119be77755efe3bde0a64e46e0c81565b6072816091565b82525050565b6000602082019050608b6000830184606b565b92915050565b600081905091905056fea26469706673582212204e02758a784bc82e5624ed8ffd35f4abc5340fb3ff08aaf7084128daf3254c3e64736f6c63430007060033";

export class PoolKeeper__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PoolKeeper> {
    return super.deploy(overrides || {}) as Promise<PoolKeeper>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoolKeeper {
    return super.attach(address) as PoolKeeper;
  }
  connect(signer: Signer): PoolKeeper__factory {
    return super.connect(signer) as PoolKeeper__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoolKeeperInterface {
    return new utils.Interface(_abi) as PoolKeeperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoolKeeper {
    return new Contract(address, _abi, signerOrProvider) as PoolKeeper;
  }
}
